# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KittiesCollection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KittiesCollection
  pod 'MultipleItemsViewModify', :git => 'https://github.com/temrov/MultipleItemsViewModify.git', :commit => 'bb660bb71aec9af29a5f11cf0967e162143f4b6e'
end
