# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KittiesCollection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KittiesCollection
  pod 'MultipleItemsViewModify', :git => 'https://github.com/temrov/MultipleItemsViewModify.git', :commit => '9cc2962a82b0242c6d19791c68102b6b34d8c4b8'
end
